name: Build Windows
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node  
        uses: actions/setup-node@v2
        with:
          node-version: "16.11.0"
      - run: npm install
      - run: npm install -g @quasar/cli
      - run: quasar build --mode electron
     # - uses: actions/upload-artifact@v2
       # with:
       #   name: grapetool_win
       #   path: D:\a\bookmarek\bookmarek\dist\electron\grapetool-win32-x64
      - run: echo "🍏 This job's status is ${{ job.status }}."